IQworkers/urls.py
from django.contrib import admin
from django.urls import path, include
import django.conf.urls
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('', include('calcapp.urls')),
    # path('', include('articleapp.urls')),
    path('', include('portfolioapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/urls.py
from django.urls import path


from .views import Articles, ArticlePage

app_name = 'articleapp'

urlpatterns = [
    path('articles/', Articles.as_view(), name='articles'),
    path('articlepage/<int:pk>/', ArticlePage.as_view(), name='articlepage'),
]

calcapp/urls.py
from django.urls import path

from .views import Calculator, get_calculation, reset_calculation

app_name = 'calcapp'

urlpatterns = [
    path('calculate/', Calculator.as_view(), name='calculate'),
    path('get_calculation/', get_calculation, name='get_calculation'),
    path('reset_calculation/', reset_calculation, name='reset_calculation'),
]

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

from .views import Main, Contacts, Command, Services, Privacy

app_name = 'mainapp'

urlpatterns = [
    path('', Main.as_view(), name='main'),
    path('contacts/', Contacts.as_view(), name='contacts'),
    path('command/', Command.as_view(), name='command'),
    path('services/', Services.as_view(), name='services'),
    path('privacy/', Privacy.as_view(), name='privacy')
]

portfolioapp/urls.py
from django.urls import path


from .views import Objects, ObjectPage

app_name = 'portfolioapp'

urlpatterns = [
    path('objects/', Objects.as_view(), name='objects'),
    path('objectpage/<int:pk>/', ObjectPage.as_view(), name='object_page'),
]

mainapp/models.py
from django.db import models


# Create your models here.

class Client(models.Model):
    class Meta:
        ordering = ['-id']

    name = models.CharField(verbose_name='Имя клиента', max_length=168)
    mail = models.CharField(verbose_name='Почта клиента', max_length=168)
    phone = models.CharField(verbose_name='Телефон клиента', max_length=168)

    def __str__(self):
        return self.name

mainapp/forms.py
from django import forms


class AppForm(forms.Form):
    name = forms.CharField(label='Имя')
    mail = forms.EmailField(label='Почта')
    phone = forms.IntegerField(label='Телефон')

mainapp/views.py
from django.shortcuts import render
from django.views.generic import View
from .forms import AppForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from .utilities import ClientHandler


appform = AppForm()

class Main(View):
    """ CBV Главной страницы """
    template_name = 'mainapp/index.html'

    def get(self, request):
        context = {
            'title': 'Главная',
            'appform': appform
        }
        return render(request, self.template_name, context)

    def post(self, request):
        new_client = ClientHandler(request)
        return HttpResponseRedirect(reverse('mainapp:main'))


class Services(View):
    """ CBV Главной страницы """
    template_name = 'mainapp/services.html'

    def get(self, request):
        context = {
            'title': 'Услуги',
            'appform': appform
        }
        return render(request, self.template_name, context)


class Contacts(View):
    """ CBV Главной страницы """
    template_name = 'mainapp/contacts.html'

    def get(self, request):
        context = {
            'title': 'Контакты',
            'appform': appform
        }
        return render(request, self.template_name, context)


class Command(View):
    """ CBV Главной страницы """
    template_name = 'mainapp/command.html'

    def get(self, request):
        context = {
            'title': 'Команда'
        }
        return render(request, self.template_name, context)


class Privacy(View):
    """ CBV страницы политики конфиденциальности """
    template_name = 'mainapp/privacy.html'

    def get(self, request):
        context = {
            'title': 'Приватность',
            'appform': appform
        }
        return render(request, self.template_name, context)

mainapp/templates/mainapp/includes/inc_footer.html
{% load static %}

<div class="container-footer">
    <div class="container-footer-buttons">
        <ul class="footer-buttons-list">
            <li class="footer-button"><a class="link-footer-text" href="{% url 'mainapp:main' %}#anchor">Главная</a></li>
            <li class="footer-button"><a class="link-footer-text" href="{% url 'mainapp:privacy' %}">Конфиденциальность</a></li>
            <li class="footer-button">
                <a class="link-footer-text" href="#">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-instagram" viewBox="0 -2 18 18">
                      <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                    </svg>
                    @iq_works
                </a>
            </li>
            <li class="footer-button"><a class="link-footer-text" href="#">info@iqworks.ru</a></li>
            <li class="footer-button"><a class="link-footer-text" href="{% url 'mainapp:contacts' %}">+7 (495) 008-81-68</a></li>
        </ul>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_js.html
{% load static %}

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'js/calculate.js' %}"></script>
<script src="{% static 'js/slider.js' %}"></script>
<script src="{% static 'js/modal.js' %}"></script>
<script src="{% static 'js/change_img.js' %}"></script>


<script type="text/javascript"> var csrf_token = '{{ csrf_token }}';</script>

mainapp/templates/mainapp/includes/inc_main_menu.html
{% load static %}

<div class="container-menu fixed">
    <div class="container-logo">
        <a href="{% url 'mainapp:main' %}"><img src="{% static 'img/logo.png' %}" alt="Главная"></a>
    </div>
    <div class="container-menu-buttons">
        <ul class="menu-buttons-list">
{#            <li class="menu-button"><a href="{% url 'mainapp:main' %}">Главная</a></li>#}
            <li class="menu-button"><a href="{% url 'mainapp:services' %}">Услуги</a></li>
            <li class="menu-button"><a href="{% url 'calcapp:calculate' %}">Стоимость</a></li>
            <li class="menu-button"><a href="{% url 'portfolioapp:objects' %}">Портфолио</a></li>
{#            <li class="menu-button"><a href="{% url 'articleapp:articles' %}">Статьи</a></li>#}
{#            <li class="menu-button"><a href="{% url 'mainapp:command' %}">Команда</a></li>#}
            <li class="menu-button"><a href="{% url 'mainapp:contacts' %}">Контакты</a></li>
        </ul>
    </div>
    <div class="container-menu-contacts">
        <ul>
            <li><a href="#">Тел. +7 (495) 008-81-68</a></li>
            <li>
                <a href="#" id="start"><img class="img-callback" src="{% static 'img/phone-icon.svg' %}"
                                  alt="Обратный звонок">Заказать звонок</a>
            </li>
        </ul>
    </div>
</div>

mainapp/templates/mainapp/includes/inc_stylesheets.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
<link rel="stylesheet" href="{% static 'css/slider.css' %}" type="text/css">
<link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">