IQworkers/urls.py
from django.contrib import admin
from django.urls import path, include
import django.conf.urls
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('', include('calcapp.urls')),
    # path('', include('articleapp.urls')),
    path('', include('portfolioapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calcapp/urls.py
from django.urls import path

from .views import Calculator, get_calculation, reset_calculation

app_name = 'calcapp'

urlpatterns = [
    path('calculate/', Calculator.as_view(), name='calculate'),
    path('get_calculation/', get_calculation, name='get_calculation'),
    path('reset_calculation/', reset_calculation, name='reset_calculation'),
]

portfolioapp/urls.py
from django.urls import path


from .views import Objects, ObjectPage

app_name = 'portfolioapp'

urlpatterns = [
    path('objects/', Objects.as_view(), name='objects'),
    path('objectpage/<int:pk>/', ObjectPage.as_view(), name='object_page'),
]

portfolioapp/models.py
from django.db import models

# Create your models here.

class PortfolioObject(models.Model):
    class Meta:
        ordering = ['-id']

    name = models.CharField(verbose_name='Название объекта', max_length=168)
    square = models.IntegerField(verbose_name='Площадь объекта, м2', default=0)
    preview = models.TextField(verbose_name='Предпросмотр', max_length=250)
    text = models.TextField(verbose_name='Текст по объекту')
    is_active = models.BooleanField(verbose_name='Актуальность объекта', default=True, db_index=True)
    add_datetime = models.DateTimeField(verbose_name='Время добавления', auto_now_add=True)
    object_status = models.BooleanField(verbose_name='Завершен ли объект', default=True, db_index=True)
    main_photo = models.ImageField(verbose_name='Главное фото', upload_to='object_photos/', null=True, blank=True)
    video = models.TextField(verbose_name='Cсылка на видео', max_length=40, blank=True)
    function_light = models.BooleanField(verbose_name='Функционал: Освещение', default=True)
    function_shutters = models.BooleanField(verbose_name='Функционал: Шторы', default=False)
    function_ventilation = models.BooleanField(verbose_name='Функционал: Вентиляция', default=False)
    function_condition = models.BooleanField(verbose_name='Функционал: Кондиционирование', default=False)
    function_warm_floors = models.BooleanField(verbose_name='Функционал: Теплые полы', default=False)
    function_security = models.BooleanField(verbose_name='Функционал: Безопасность', default=False)
    function_remote = models.BooleanField(verbose_name='Функционал: Удаленное управление', default=False)
    function_voice_control = models.BooleanField(verbose_name='Функционал: Голосовые помощники', default=False)

    def __str__(self):
        return self.name


class PortfolioImage(models.Model):
    object = models.ForeignKey(PortfolioObject, on_delete=models.CASCADE,
                               verbose_name='Объект', related_name='object', null=True, db_index=True)
    image = models.FileField(upload_to='object_photos/', null=True)
    is_active = models.BooleanField(verbose_name='Актуальность фото', default=True, db_index=True)

    def __str__(self):
        return self.image.name

portfolioapp/views.py
from django.shortcuts import render
from django.views.generic import View, ListView, DetailView
from portfolioapp.models import PortfolioObject, PortfolioImage
from mainapp.forms import AppForm

appform = AppForm()


class Objects(ListView):
    """ CBV Страницы с портфолио """
    model = PortfolioObject
    template_name = 'portfolioapp/objects.html'
    context_object_name = 'portfolio'
    extra_context = {
        'title': 'Портфолио',
        'appform': appform
    }


class ObjectPage(DetailView):
    """ CBV Страницы объекта """
    model = PortfolioObject
    template_name = 'portfolioapp/objectpage.html'
    extra_context = {
        'title': 'Объект',
        'appform': appform
    }

    def get(self, request, pk):
        object = PortfolioObject.objects.filter(id=pk).first()
        context = {
            'title': 'Объект',
            'object': object,
            'photos': PortfolioImage.objects.filter(object=object),
            'appform': appform
        }
        return render(request, self.template_name, context)

portfolioapp/templates/portfolioapp/objectpage.html
{% extends "mainapp/base.html" %}
{% load static %}
{#{% load project_tags %}#}
{% block title %}{{ title|title }}{% endblock %}
{% block content %}
    <div class="content-container add-border">
        <div class="header-object-text add-border">{{ object.preview }}, <span class="red">{{ object.square }}м2</span></div>
        <div class="container-object-slider">
            <div class="slideshow-container">
<!--                {% for item_photo in photos %}-->
<!--                    <div class="mySlides fade">-->
<!--                        <div class="numbertext">{{ forloop.counter }} / {{ photos|length }}</div>-->
<!--                        <img src="{{ item_photo.image.url }}" style="width:100%">-->
<!--                        <div class="text"></div>-->
<!--                    </div>-->
<!--                {% endfor %}-->
                <div class="mySlides fade">
                    <div class="numbertext">1 / 3</div>
                    <img src="{% static 'img/img_example_1.png' %}" style="width:100%" alt="">
                    <div class="text"></div>
                </div>
                <div class="mySlides fade">
                    <div class="numbertext">2 / 3</div>
                    <img src="{% static 'img/img_example_2.png' %}" style="width:100%" alt="">
                    <div class="text"></div>
                </div>
                <div class="mySlides fade">
                    <div class="numbertext">3 / 3</div>
                    <img src="{% static 'img/img_example_3.png' %}" style="width:100%" alt="">
                    <div class="text"></div>
                </div>

                <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
                <a class="next" onclick="plusSlides(1)">&#10095;</a>
                </div>
                <br>
                <div style="text-align:center">
                {% for item_photo in photos %}
                    <span class="dot" onclick="currentSlide({{ forloop.counter }})"></span>
                {% endfor %}
            </div>
        </div>
        <div class="object-text">{{ object.text }}</div>
    </div>
{% endblock %}

portfolioapp/templates/portfolioapp/objects.html
{% extends "mainapp/base.html" %}
{% load static %}
{#{% load project_tags %}#}
{% block title %}{{ title|title }}{% endblock %}
{% block content %}
    <div class="header-text add-border">Портфолио</div>
    {% for object in object_list %}
        <div class="content-container add-border">
            {% if object.is_active %}
                <div class="object-preview">
                    {% if forloop.counter|divisibleby:"2" %}
                        <div class="container-object-preview-content add-border">
                    {% else %}
                        <div class="container-object-preview-content reverse add-border">
                    {% endif %}
                            <div class="container-img-object-preview add-border">
                                <img class="img-object-preview add-border" src="{% static 'img/img_example_1.png' %}" alt="Фото объекта">
                            </div>
                            <div class="obj-info-preview">
                                <div class="container-object-info add-border">
                                    <img class="img-object-preview-count add-border for-change" src="{% get_static_prefix %}img/{{forloop.counter}}.png" alt="Фото объекта">
                                    <div class="preview-object-about add-border">
                                        <div class="container-object-preview-name add-border">
                                            <p>{{ object.preview }}, <span class="red">{{ object.square }}м2</span></p>
                                        </div>
                                        <div class="container-object-preview-text add-border">
                                            <p>{{ object.text|truncatewords:10 }}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="container-object-preview-button-next add-border">
                                    <div class="buttons-on-preview">
                                        {% if object.video %}
                                            <a class="">
                                                <img class="img-icon-video" src="{% static 'img/play_video.svg' %}" alt="">
                                            </a>
                                        {% endif %}
                                            <a class="" href="{% url 'portfolioapp:object_page' object.pk %}">
                                                Подробнее
                                            </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}