IQworkers/urls.py
from django.contrib import admin
from django.urls import path, include
import django.conf.urls
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('', include('calcapp.urls')),
    # path('', include('articleapp.urls')),
    path('', include('portfolioapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articleapp/urls.py
from django.urls import path


from .views import Articles, ArticlePage

app_name = 'articleapp'

urlpatterns = [
    path('articles/', Articles.as_view(), name='articles'),
    path('articlepage/<int:pk>/', ArticlePage.as_view(), name='articlepage'),
]

calcapp/urls.py
from django.urls import path

from .views import Calculator, get_calculation, reset_calculation

app_name = 'calcapp'

urlpatterns = [
    path('calculate/', Calculator.as_view(), name='calculate'),
    path('get_calculation/', get_calculation, name='get_calculation'),
    path('reset_calculation/', reset_calculation, name='reset_calculation'),
]

articleapp/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    class Meta:
        verbose_name = 'статья'
        verbose_name_plural = 'статьи'
        ordering = ['-add_datetime']

    name = models.CharField(verbose_name='Название статьи', max_length=168)
    main_image = models.ImageField(verbose_name='Изображение для статьи', blank=True, upload_to='article_photos/')
    preview = models.TextField(verbose_name='Предпросмотр', max_length=250)
    text = models.TextField(verbose_name='Текст статьи')

    is_active = models.BooleanField(verbose_name='Актуальность статьи', default=True, db_index=True)
    add_datetime = models.DateTimeField(verbose_name='Время добавления', auto_now_add=True)

    def __str__(self):
        return f'{self.name}'

articleapp/forms.py
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField
from articleapp.models import Article
from django import forms
from django.forms import ModelForm


class ArticleCreationForm(ModelForm):
    class Meta:
        model = Article
        fields = ['name', 'preview', 'text', 'tag', 'hub', 'image']
        widgets = {
            'text': SummernoteWidget(),
        }

    def __init__(self, *args, **kwargs):
        super(ArticleCreationForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            if field_name in ['name', 'preview', 'hub']:
                field.required = True
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['style'] = 'width: 1000px;'

articleapp/views.py
from django.shortcuts import render
from django.views.generic import View, ListView
from articleapp.models import Article
from mainapp.forms import AppForm

appform = AppForm()


class Articles(ListView):
    """ CBV Страницы со статьями """
    model = Article
    template_name = 'articleapp/articles.html'
    context_object_name = 'articles'
    extra_context = {
        'title': 'Статьи',
        'appform': appform
    }


class ArticlePage(View):
    """ CBV Страницы статьи """
    template_name = 'articleapp/articlepage.html'
    extra_context = {'title': 'Статья'}

    def get(self, request, pk):
        article = Article.objects.filter(id=pk).first()
        context = {
            'title': 'Статья',
            'article': article,
            'appform': appform
        }
        return render(request, self.template_name, context)

articleapp/templates/articleapp/articlepage.html
{% extends "mainapp/base.html" %}
{% load static %}
{#{% load project_tags %}#}
{% block title %}{{ title|title }}{% endblock %}
{% block content %}
    <div class="content-container add-border">
        <div class="header-object-text add-border">{{ article.preview }}</div>
        <div class="text">{{ article.text|safe|linebreaks }}</div>
    </div>

{% endblock %}

articleapp/templates/articleapp/articles.html
{% extends "mainapp/base.html" %}
{% load static %}
{#{% load project_tags %}#}
{% block title %}{{ title|title }}{% endblock %}
{% block content %}
    <div class="content-container add-border">
        <div class="header-text add-border">Статьи</div>
        {% for article in object_list %}
            {% if article.is_active %}
                <div class="object-preview add-border">
                    <div class="container-object-preview-name add-border">
                        <p>{{ article.preview }}</p>
                    </div>
                    <div class="container-object-preview-content add-border">
                        <div class="container-img-object-preview add-border">
                            {% if article.main_photo %}
                                <img class="img-object-preview add-border" src="{{ article.main_photo.url }}" alt="Фото объекта">
                            {% else %}
                                <img class="img-object-preview add-border" src="{% static 'img/Example-photo.jpg' %}" alt="Фото объекта">
                            {% endif %}
                        </div>
                        <div class="container-object-info add-border">
                            <div class="preview-object-functions add-border">
                                <div class="container-object-preview-button-next  add-border">
                                    <div class="buttons-on-preview">
                                        <a class="button-preview-detailed" href="{% url 'articleapp:articlepage' article.pk %}">
                                            Подробнее
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}